import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import '../../../../core/constants/app_constants.dart';
import '../../../../core/router/route_names.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_dimensions.dart';
import '../../../../core/utils/formatters.dart';
import '../../../../core/utils/snackbar_helper.dart';
import '../../../../shared/widgets/cached_image.dart';
import '../../../auth/providers/auth_provider.dart';
import '../../barber/models/barber_model.dart';
import '../../barber/providers/barber_provider.dart';
import '../../booking/models/booking_model.dart';
import '../../booking/providers/booking_provider.dart';
import '../../service/models/service_model.dart';
import '../../service/providers/service_provider.dart';

/// Booking Creation screen with multi-step wizard flow.
///
/// Steps:
/// 1. Select Barber (from Firestore active barbers)
/// 2. Select Service (from Firestore active services)
/// 3. Select Date (calendar picker, no past dates, max 30 days)
/// 4. Select Time (available time slots based on barber working hours)
/// 5. Add Notes (optional)
/// 6. Review & Confirm (summary with total price)
///
/// Features:
/// - Accepts optional `barberId` query parameter to pre-select barber
/// - Validates each step before proceeding
/// - Creates booking in Firestore with denormalized display fields
/// - Navigates to booking history on success
class BookingCreateScreen extends ConsumerStatefulWidget {
  /// Optional pre-selected barber ID (from barber detail "Book Now")
  final String? initialBarberId;

  const BookingCreateScreen({super.key, this.initialBarberId});

  @override
  ConsumerState<BookingCreateScreen> createState() => _BookingCreateScreenState();
}

class _BookingCreateScreenState extends ConsumerState<BookingCreateScreen> {
  int _currentStep = 0;
  bool _isSubmitting = false;

  // Selected values
  BarberModel? _selectedBarber;
  ServiceModel? _selectedService;
  DateTime? _selectedDate;
  String? _selectedTime;
  final _notesController = TextEditingController();

  @override
  void initState() {
    super.initState();
    // Pre-select barber if barberId is provided
    if (widget.initialBarberId != null && widget.initialBarberId!.isNotEmpty) {
      _loadInitialBarber(widget.initialBarberId!);
    }
  }

  @override
  void dispose() {
    _notesController.dispose();
    super.dispose();
  }

  /// Load barber data when initialBarberId is provided
  void _loadInitialBarber(String barberId) {
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final barber = await ref.read(barberByIdProvider(barberId).future);
      if (barber != null && mounted) {
        setState(() {
          _selectedBarber = barber;
          if (_currentStep == 0) _currentStep = 1; // Skip to service selection
        });
      }
    });
  }

  /// Maximum bookable date (30 days from today)
  DateTime get _maxDate =>
      DateTime.now().add(const Duration(days: AppConstants.maxBookingDaysAhead));

  /// Minimum bookable date (today)
  DateTime get _minDate {
    final now = DateTime.now();
    return DateTime(now.year, now.month, now.day);
  }

  /// Create the booking in Firestore
  Future<void> _handleCreateBooking() async {
    if (_selectedBarber == null ||
        _selectedService == null ||
        _selectedDate == null ||
        _selectedTime == null) {
      return;
    }

    setState(() => _isSubmitting = true);

    final user = ref.read(authStateProvider).whenOrNull(data: (u) => u);
    if (user == null) {
      setState(() => _isSubmitting = false);
      SnackbarHelper.error(context, 'You must be logged in to book');
      return;
    }

    try {
      final booking = BookingModel(
        id: '', // Will be generated by Firestore
        customerId: user.uid,
        barberId: _selectedBarber!.id,
        serviceId: _selectedService!.id,
        tanggal: _selectedDate!,
        jam: _selectedTime!,
        status: AppConstants.statusPending,
        catatan: _notesController.text.trim().isEmpty
            ? null
            : _notesController.text.trim(),
        totalHarga: _selectedService!.harga,
        createdAt: DateTime.now(),
        // Denormalized fields for display
        customerNama: user.nama,
        barberNama: _selectedBarber!.nama,
        serviceNama: _selectedService!.nama,
        barberFoto: _selectedBarber!.foto,
      );

      await ref.read(bookingServiceProvider).createBooking(booking);

      if (!mounted) return;

      SnackbarHelper.success(context, 'Booking created successfully!');
      context.go(RouteNames.customerBooking);
    } catch (e) {
      if (!mounted) return;
      setState(() => _isSubmitting = false);
      SnackbarHelper.error(context, e.toString());
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundLight,
      appBar: AppBar(
        title: const Text('Book Appointment'),
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios),
          onPressed: () => context.pop(),
        ),
      ),
      body: Column(
        children: [
          // Step indicator
          _buildStepIndicator(),

          // Step content
          Expanded(
            child: AnimatedSwitcher(
              duration: const Duration(milliseconds: 300),
              child: _buildCurrentStep(),
            ),
          ),
        ],
      ),
      // Bottom navigation buttons
      bottomNavigationBar: _buildBottomBar(),
    );
  }

  // ─── Step Indicator ───────────────────────────────────────────────
  Widget _buildStepIndicator() {
    final steps = ['Barber', 'Service', 'Date', 'Time', 'Notes'];

    return Container(
      padding: const EdgeInsets.symmetric(
        horizontal: AppDimensions.spacingXL,
        vertical: AppDimensions.spacingMD,
      ),
      color: AppColors.white,
      child: Row(
        children: List.generate(steps.length, (index) {
          final isActive = index <= _currentStep;
          final isCompleted = index < _currentStep;

          return Expanded(
            child: Column(
              children: [
                Container(
                  width: 28,
                  height: 28,
                  decoration: BoxDecoration(
                    color: isActive ? AppColors.primaryBlack : AppColors.lightGrey,
                    shape: BoxShape.circle,
                  ),
                  child: Center(
                    child: isCompleted
                        ? const Icon(Icons.check, color: Colors.white, size: 16)
                        : Text(
                            '${index + 1}',
                            style: TextStyle(
                              color: isActive ? Colors.white : AppColors.darkGrey,
                              fontSize: 12,
                              fontWeight: FontWeight.w600,
                            ),
                          ),
                  ),
                ),
                const SizedBox(height: 4),
                Text(
                  steps[index],
                  style: TextStyle(
                    fontSize: 10,
                    color: isActive ? AppColors.primaryBlack : AppColors.darkGrey,
                    fontWeight: isActive ? FontWeight.w600 : FontWeight.normal,
                  ),
                ),
              ],
            ),
          );
        }),
      ),
    );
  }

  // ─── Current Step Content ─────────────────────────────────────────
  Widget _buildCurrentStep() {
    switch (_currentStep) {
      case 0:
        return _buildSelectBarber();
      case 1:
        return _buildSelectService();
      case 2:
        return _buildSelectDate();
      case 3:
        return _buildSelectTime();
      case 4:
        return _buildReviewAndConfirm();
      default:
        return _buildSelectBarber();
    }
  }

  // ─── Step 0: Select Barber ────────────────────────────────────────
  Widget _buildSelectBarber() {
    final barbersAsync = ref.watch(activeBarbersProvider);

    return barbersAsync.when(
      loading: () => const Center(child: CircularProgressIndicator()),
      error: (_, _) => const Center(child: Text('Failed to load barbers')),
      data: (barbers) {
        if (barbers.isEmpty) {
          return const Center(child: Text('No barbers available'));
        }
        return ListView.builder(
          padding: const EdgeInsets.all(AppDimensions.spacingXL),
          itemCount: barbers.length,
          itemBuilder: (context, index) {
            final barber = barbers[index];
            final isSelected = _selectedBarber?.id == barber.id;

            return GestureDetector(
              onTap: () => setState(() => _selectedBarber = barber),
              child: Container(
                margin: const EdgeInsets.only(bottom: AppDimensions.spacingMD),
                padding: const EdgeInsets.all(AppDimensions.spacingMD),
                decoration: BoxDecoration(
                  color: AppColors.white,
                  borderRadius: BorderRadius.circular(AppDimensions.radiusLG),
                  border: Border.all(
                    color: isSelected
                        ? AppColors.gold
                        : AppColors.lightGrey,
                    width: isSelected ? 2 : 1,
                  ),
                  boxShadow: isSelected ? AppDimensions.shadowMD : AppDimensions.shadowSM,
                ),
                child: Row(
                  children: [
                    // Photo
                    barber.foto != null
                        ? CachedImage(
                            imageUrl: barber.foto!,
                            width: 56,
                            height: 56,
                            borderRadius: 28,
                            fit: BoxFit.cover,
                          )
                        : CircleAvatar(
                            radius: 28,
                            backgroundColor: AppColors.lightGrey,
                            child: const Icon(Icons.person, color: AppColors.mediumGrey),
                          ),
                    const SizedBox(width: AppDimensions.spacingMD),
                    // Info
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            barber.nama,
                            style: const TextStyle(
                              fontWeight: FontWeight.w700,
                              fontSize: 16,
                            ),
                          ),
                          Text(
                            barber.spesialis,
                            style: TextStyle(color: AppColors.darkGrey, fontSize: 13),
                          ),
                          const SizedBox(height: 4),
                          Row(
                            children: [
                              const Icon(Icons.star, color: AppColors.starFilled, size: 14),
                              const SizedBox(width: 2),
                              Text(
                                Formatters.rating(barber.rating),
                                style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 12),
                              ),
                              const SizedBox(width: AppDimensions.spacingSM),
                              Text(
                                '${barber.pengalaman} years exp',
                                style: TextStyle(color: AppColors.darkGrey, fontSize: 12),
                              ),
                            ],
                          ),
                        ],
                      ),
                    ),
                    // Check icon
                    if (isSelected)
                      Container(
                        width: 24,
                        height: 24,
                        decoration: const BoxDecoration(
                          color: AppColors.successGreen,
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.check, color: Colors.white, size: 16),
                      ),
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  // ─── Step 1: Select Service ───────────────────────────────────────
  Widget _buildSelectService() {
    final servicesAsync = ref.watch(activeServicesProvider);

    return servicesAsync.when(
      loading: () => const Center(
        child: CircularProgressIndicator(),
      ),

      error: (error, stackTrace) {
        debugPrint('=================================');
        debugPrint('SERVICE ERROR');
        debugPrint(error.toString());
        debugPrint(stackTrace.toString());
        debugPrint('=================================');

        return Center(
          child: Padding(
            padding: const EdgeInsets.all(20),
            child: Text(
              error.toString(),
              textAlign: TextAlign.center,
              style: const TextStyle(
                color: Colors.red,
                fontSize: 14,
              ),
            ),
          ),
        );
      },
      data: (services) {
        if (services.isEmpty) {
          return const Center(child: Text('No services available'));
        }
        return ListView.builder(
          padding: const EdgeInsets.all(AppDimensions.spacingXL),
          itemCount: services.length,
          itemBuilder: (context, index) {
            final service = services[index];
            final isSelected = _selectedService?.id == service.id;

            return GestureDetector(
              onTap: () => setState(() => _selectedService = service),
              child: Container(
                margin: const EdgeInsets.only(bottom: AppDimensions.spacingMD),
                padding: const EdgeInsets.all(AppDimensions.spacingLG),
                decoration: BoxDecoration(
                  color: AppColors.white,
                  borderRadius: BorderRadius.circular(AppDimensions.radiusLG),
                  border: Border.all(
                    color: isSelected ? AppColors.gold : AppColors.lightGrey,
                    width: isSelected ? 2 : 1,
                  ),
                  boxShadow: isSelected ? AppDimensions.shadowMD : AppDimensions.shadowSM,
                ),
                child: Row(
                  children: [
                    // Icon
                    Container(
                      width: 48,
                      height: 48,
                      decoration: BoxDecoration(
                        color: AppColors.gold.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(12),
                      ),
                      child: const Icon(Icons.content_cut, color: AppColors.gold, size: 24),
                    ),
                    const SizedBox(width: AppDimensions.spacingMD),
                    // Info
                    Expanded(
                      child: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(
                            service.nama,
                            style: const TextStyle(
                              fontWeight: FontWeight.w700,
                              fontSize: 16,
                            ),
                          ),
                          Text(
                            '${service.durasi} minutes',
                            style: TextStyle(color: AppColors.darkGrey, fontSize: 13),
                          ),
                        ],
                      ),
                    ),
                    // Price
                    Text(
                      Formatters.currency(service.harga),
                      style: const TextStyle(
                        fontWeight: FontWeight.w700,
                        fontSize: 16,
                        color: AppColors.primaryBlack,
                      ),
                    ),
                    if (isSelected) ...[
                      const SizedBox(width: AppDimensions.spacingSM),
                      Container(
                        width: 24,
                        height: 24,
                        decoration: const BoxDecoration(
                          color: AppColors.successGreen,
                          shape: BoxShape.circle,
                        ),
                        child: const Icon(Icons.check, color: Colors.white, size: 16),
                      ),
                    ],
                  ],
                ),
              ),
            );
          },
        );
      },
    );
  }

  // ─── Step 2: Select Date ──────────────────────────────────────────
  Widget _buildSelectDate() {
    return Padding(
      padding: const EdgeInsets.all(AppDimensions.spacingXL),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Select Date',
            style: Theme.of(context).textTheme.titleLarge,
          ),
          const SizedBox(height: AppDimensions.spacingSM),
          Text(
            'Choose a date within the next 30 days',
            style: TextStyle(color: AppColors.darkGrey, fontSize: 14),
          ),
          const SizedBox(height: AppDimensions.spacingLG),
          // Date display card
          GestureDetector(
            onTap: () => _pickDate(),
            child: Container(
              width: double.infinity,
              padding: const EdgeInsets.all(AppDimensions.spacingXL),
              decoration: BoxDecoration(
                color: AppColors.white,
                borderRadius: BorderRadius.circular(AppDimensions.radiusLG),
                border: Border.all(
                  color: _selectedDate != null ? AppColors.gold : AppColors.lightGrey,
                  width: _selectedDate != null ? 2 : 1,
                ),
                boxShadow: AppDimensions.shadowSM,
              ),
              child: Row(
                children: [
                  Container(
                    width: 56,
                    height: 56,
                    decoration: BoxDecoration(
                      color: AppColors.gold.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(16),
                    ),
                    child: const Icon(
                      Icons.calendar_today,
                      color: AppColors.gold,
                      size: 28,
                    ),
                  ),
                  const SizedBox(width: AppDimensions.spacingLG),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          _selectedDate != null
                              ? Formatters.dateFull(_selectedDate)
                              : 'Tap to select date',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.w700,
                            color: _selectedDate != null
                                ? AppColors.primaryBlack
                                : AppColors.mediumGrey,
                          ),
                        ),
                        if (_selectedDate != null)
                          Text(
                            _getDayName(_selectedDate!),
                            style: TextStyle(color: AppColors.darkGrey, fontSize: 14),
                          ),
                      ],
                    ),
                  ),
                  const Icon(Icons.chevron_right, color: AppColors.mediumGrey),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// Open date picker dialog
  Future<void> _pickDate() async {
    final picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate ?? _minDate,
      firstDate: _minDate,
      lastDate: _maxDate,
      builder: (context, child) {
        return Theme(
          data: Theme.of(context).copyWith(
            colorScheme: const ColorScheme.light(
              primary: AppColors.primaryBlack,
              onPrimary: Colors.white,
              onSurface: AppColors.charcoal,
            ),
          ),
          child: child!,
        );
      },
    );
    if (picked != null) {
      setState(() {
        _selectedDate = picked;
        _selectedTime = null; // Reset time when date changes
      });
    }
  }

  /// Get day name from DateTime
  String _getDayName(DateTime date) {
    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    return days[date.weekday - 1];
  }

  // ─── Step 3: Select Time ──────────────────────────────────────────
  Widget _buildSelectTime() {
    if (_selectedBarber == null || _selectedDate == null) {
      return const Center(child: Text('Please select barber and date first'));
    }

    final slotsAsync = ref.watch(
      availableTimeSlotsProvider((
        barberId: _selectedBarber!.id,
        tanggal: _selectedDate!,
        jamMasuk: _selectedBarber!.jamMasuk,
        jamPulang: _selectedBarber!.jamPulang,
      )),
    );

    return Padding(
      padding: const EdgeInsets.all(AppDimensions.spacingXL),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Select Time',
            style: Theme.of(context).textTheme.titleLarge,
          ),
          const SizedBox(height: AppDimensions.spacingSM),
          Text(
            'Available time slots for ${_selectedBarber!.nama}',
            style: TextStyle(color: AppColors.darkGrey, fontSize: 14),
          ),
          const SizedBox(height: AppDimensions.spacingLG),
          Expanded(
            child: slotsAsync.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (_, _) => const Center(child: Text('Failed to load time slots')),
              data: (slots) {
                if (slots.isEmpty) {
                  return const Center(
                    child: Text('No available time slots for this date'),
                  );
                }
                return GridView.builder(
                  gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
                    crossAxisCount: 3,
                    crossAxisSpacing: 8,
                    mainAxisSpacing: 8,
                    childAspectRatio: 2.5,
                  ),
                  itemCount: slots.length,
                  itemBuilder: (context, index) {
                    final slot = slots[index];
                    final isSelected = _selectedTime == slot;

                    return GestureDetector(
                      onTap: () => setState(() => _selectedTime = slot),
                      child: Container(
                        decoration: BoxDecoration(
                          color: isSelected
                              ? AppColors.primaryBlack
                              : AppColors.white,
                          borderRadius: BorderRadius.circular(AppDimensions.radiusMD),
                          border: Border.all(
                            color: isSelected
                                ? AppColors.primaryBlack
                                : AppColors.lightGrey,
                          ),
                        ),
                        child: Center(
                          child: Text(
                            Formatters.time12h(slot),
                            style: TextStyle(
                              color: isSelected ? Colors.white : AppColors.charcoal,
                              fontWeight: FontWeight.w600,
                              fontSize: 14,
                            ),
                          ),
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  // ─── Step 4: Review & Confirm ─────────────────────────────────────
  Widget _buildReviewAndConfirm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(AppDimensions.spacingXL),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Review Booking',
            style: Theme.of(context).textTheme.titleLarge,
          ),
          const SizedBox(height: AppDimensions.spacingSM),
          Text(
            'Please review your booking details',
            style: TextStyle(color: AppColors.darkGrey, fontSize: 14),
          ),
          const SizedBox(height: AppDimensions.spacingLG),

          // Summary card
          Container(
            padding: const EdgeInsets.all(AppDimensions.spacingLG),
            decoration: BoxDecoration(
              color: AppColors.white,
              borderRadius: BorderRadius.circular(AppDimensions.radiusLG),
              boxShadow: AppDimensions.shadowMD,
            ),
            child: Column(
              children: [
                // Barber
                _buildSummaryRow(
                  icon: Icons.person,
                  label: 'Barber',
                  value: _selectedBarber?.nama ?? '-',
                ),
                const Divider(height: 24),

                // Service
                _buildSummaryRow(
                  icon: Icons.content_cut,
                  label: 'Service',
                  value: _selectedService?.nama ?? '-',
                  subtitle: '${_selectedService?.durasi ?? 0} min',
                ),
                const Divider(height: 24),

                // Date
                _buildSummaryRow(
                  icon: Icons.calendar_today,
                  label: 'Date',
                  value: _selectedDate != null
                      ? Formatters.dateFull(_selectedDate)
                      : '-',
                  subtitle: _selectedDate != null ? _getDayName(_selectedDate!) : null,
                ),
                const Divider(height: 24),

                // Time
                _buildSummaryRow(
                  icon: Icons.schedule,
                  label: 'Time',
                  value: _selectedTime != null
                      ? Formatters.time12h(_selectedTime)
                      : '-',
                ),
                const Divider(height: 24),

                // Notes
                _buildNotesField(),
                const Divider(height: 24),

                // Total
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    const Text(
                      'Total',
                      style: TextStyle(
                        fontSize: 18,
                        fontWeight: FontWeight.w700,
                      ),
                    ),
                    Text(
                      Formatters.currency(_selectedService?.harga ?? 0),
                      style: const TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.w800,
                        color: AppColors.gold,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildSummaryRow({
    required IconData icon,
    required String label,
    required String value,
    String? subtitle,
  }) {
    return Row(
      children: [
        Container(
          width: 36,
          height: 36,
          decoration: BoxDecoration(
            color: AppColors.gold.withValues(alpha: 0.1),
            borderRadius: BorderRadius.circular(10),
          ),
          child: Icon(icon, color: AppColors.gold, size: 18),
        ),
        const SizedBox(width: AppDimensions.spacingMD),
        Expanded(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                label,
                style: TextStyle(color: AppColors.darkGrey, fontSize: 12),
              ),
              Text(
                value,
                style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 15),
              ),
              if (subtitle != null)
                Text(
                  subtitle,
                  style: TextStyle(color: AppColors.darkGrey, fontSize: 12),
                ),
            ],
          ),
        ),
      ],
    );
  }

  Widget _buildNotesField() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Row(
          children: [
            Container(
              width: 36,
              height: 36,
              decoration: BoxDecoration(
                color: AppColors.gold.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(10),
              ),
              child: const Icon(Icons.notes, color: AppColors.gold, size: 18),
            ),
            const SizedBox(width: AppDimensions.spacingMD),
            const Text(
              'Notes (optional)',
              style: TextStyle(color: AppColors.darkGrey, fontSize: 12),
            ),
          ],
        ),
        const SizedBox(height: AppDimensions.spacingSM),
        TextField(
          controller: _notesController,
          maxLines: 3,
          maxLength: 200,
          decoration: InputDecoration(
            hintText: 'Any special requests or notes...',
            filled: true,
            fillColor: AppColors.backgroundLight,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppDimensions.radiusMD),
              borderSide: BorderSide.none,
            ),
          ),
        ),
      ],
    );
  }

  // ─── Bottom Navigation Bar ────────────────────────────────────────
  Widget _buildBottomBar() {
    return Container(
      padding: const EdgeInsets.fromLTRB(
        AppDimensions.spacingXL,
        AppDimensions.spacingMD,
        AppDimensions.spacingXL,
        AppDimensions.spacingXL,
      ),
      decoration: BoxDecoration(
        color: AppColors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: Row(
        children: [
          // Back button (hidden on first step)
          if (_currentStep > 0)
            Padding(
              padding: const EdgeInsets.only(right: AppDimensions.spacingMD),
              child: OutlinedButton(
                onPressed: _isSubmitting ? null : () => setState(() => _currentStep--),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
                  side: const BorderSide(color: AppColors.lightGrey),
                ),
                child: const Text('Back'),
              ),
            ),

          // Next/Confirm button
          Expanded(
            child: SizedBox(
              height: AppDimensions.buttonHeightLG,
              child: ElevatedButton(
                onPressed: _canProceed()
                    ? (_currentStep == 4 ? _handleCreateBooking : _nextStep)
                    : null,
                style: ElevatedButton.styleFrom(
                  backgroundColor: AppColors.primaryBlack,
                  foregroundColor: AppColors.white,
                  disabledBackgroundColor: AppColors.lightGrey,
                ),
                child: _isSubmitting
                    ? const SizedBox(
                        width: 24,
                        height: 24,
                        child: CircularProgressIndicator(
                          color: AppColors.gold,
                          strokeWidth: 2,
                        ),
                      )
                    : Text(
                        _currentStep == 4 ? 'Confirm Booking' : 'Next',
                        style: const TextStyle(
                          fontSize: 16,
                          fontWeight: FontWeight.w700,
                        ),
                      ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  /// Check if the user can proceed to the next step
  bool _canProceed() {
    if (_isSubmitting) return false;
    switch (_currentStep) {
      case 0:
        return _selectedBarber != null;
      case 1:
        return _selectedService != null;
      case 2:
        return _selectedDate != null;
      case 3:
        return _selectedTime != null;
      case 4:
        return true;
      default:
        return false;
    }
  }

  /// Move to the next step
  void _nextStep() {
    if (_canProceed() && _currentStep < 4) {
      setState(() => _currentStep++);
    }
  }
}
