import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:flutter_animate/flutter_animate.dart';
import '../../../../core/router/route_names.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_dimensions.dart';
import '../../../../core/utils/formatters.dart';
import '../../../../core/utils/snackbar_helper.dart';
import '../../../../core/widgets/loading_widget.dart';
import '../../../../shared/widgets/cached_image.dart';
import '../../../auth/providers/auth_provider.dart';
import '../../booking/models/booking_model.dart';
import '../../booking/providers/booking_provider.dart';
import '../models/review_model.dart';
import '../providers/review_provider.dart';

/// Rating screen for customers to leave feedback after a completed booking.
///
/// Features:
/// - 5-star rating widget (interactive, tappable)
/// - Comment/review text field (optional, max 500 chars)
/// - Shows booking summary (barber, service, date)
/// - Submits review to Firestore and updates barber's average rating
/// - Prevents duplicate reviews (checks hasRated field)
class RatingScreen extends ConsumerStatefulWidget {
  final String bookingId;

  const RatingScreen({super.key, required this.bookingId});

  @override
  ConsumerState<RatingScreen> createState() => _RatingScreenState();
}

class _RatingScreenState extends ConsumerState<RatingScreen> {
  int _selectedRating = 0;
  final _commentController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _commentController.dispose();
    super.dispose();
  }

  /// Submit the review to Firestore
  Future<void> _submitReview(BookingModel booking) async {
    if (_selectedRating == 0) {
      SnackbarHelper.error(context, 'Please select a rating');
      return;
    }

    setState(() => _isSubmitting = true);

    final user = ref.read(authStateProvider).whenOrNull(data: (u) => u);
    if (user == null) {
      setState(() => _isSubmitting = false);
      SnackbarHelper.error(context, 'You must be logged in to submit a review');
      return;
    }

    try {
      final review = ReviewModel(
        id: '', // Will be generated by Firestore
        bookingId: booking.id,
        customerId: user.uid,
        barberId: booking.barberId,
        rating: _selectedRating,
        komentar: _commentController.text.trim(),
        customerNama: user.nama,
        customerPhoto: user.photo,
        createdAt: DateTime.now(),
      );

      await ref.read(reviewServiceProvider).createReview(review);

      if (mounted) {
        SnackbarHelper.success(context, 'Thank you for your review!');
        context.go(RouteNames.customerBooking);
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isSubmitting = false);
        SnackbarHelper.error(context, 'Failed to submit review: $e');
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final user = ref.watch(authStateProvider).whenOrNull(data: (u) => u);
    if (user == null) {
      return Scaffold(
        appBar: AppBar(title: const Text('Rate Your Experience')),
        body: const Center(child: Text('Please login to rate')),
      );
    }

    // Fetch the booking data
    final bookingsAsync = ref.watch(customerBookingsProvider(user.uid));

    return Scaffold(
      backgroundColor: AppColors.backgroundLight,
      appBar: AppBar(
        title: const Text('Rate Your Experience'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () => context.pop(),
        ),
      ),
      body: bookingsAsync.when(
        loading: () => const LoadingWidget(message: 'Loading booking...'),
        error: (_, _) => const Center(child: Text('Failed to load booking')),
        data: (bookings) {
          // Find the specific booking
          final booking = bookings.where((b) => b.id == widget.bookingId).firstOrNull;
          if (booking == null) {
            return const Center(child: Text('Booking not found'));
          }

          // Check if already rated
          if (booking.hasRated) {
            return _buildAlreadyRated(context);
          }

          return SingleChildScrollView(
            padding: const EdgeInsets.all(AppDimensions.spacingXL),
            child: Column(
              children: [
                const SizedBox(height: AppDimensions.spacingLG),

                // ─── Booking Summary Card ─────────────────────────────
                _buildBookingSummary(booking),
                const SizedBox(height: AppDimensions.spacingXXL),

                // ─── Star Rating Widget ────────────────────────────────
                _buildStarRating(),
                const SizedBox(height: AppDimensions.spacingSM),

                // Rating label
                Text(
                  _getRatingLabel(_selectedRating),
                  style: TextStyle(
                    color: AppColors.darkGrey,
                    fontSize: 14,
                    fontWeight: FontWeight.w500,
                  ),
                ).animate().fadeIn(),
                const SizedBox(height: AppDimensions.spacingXXL),

                // ─── Comment Field ────────────────────────────────────
                _buildCommentField(),
                const SizedBox(height: AppDimensions.spacingXXXL),

                // ─── Submit Button ────────────────────────────────────
                _buildSubmitButton(booking),
              ],
            ),
          );
        },
      ),
    );
  }

  // ─── Booking Summary Card ──────────────────────────────────────────
  Widget _buildBookingSummary(BookingModel booking) {
    return Container(
      padding: const EdgeInsets.all(AppDimensions.spacingLG),
      decoration: BoxDecoration(
        color: AppColors.white,
        borderRadius: BorderRadius.circular(AppDimensions.radiusLG),
        boxShadow: AppDimensions.shadowMD,
      ),
      child: Row(
        children: [
          // Barber photo
          booking.barberFoto != null
              ? CachedImage(
                  imageUrl: booking.barberFoto!,
                  width: 56,
                  height: 56,
                  borderRadius: 28,
                  fit: BoxFit.cover,
                )
              : CircleAvatar(
                  radius: 28,
                  backgroundColor: AppColors.gold.withValues(alpha: 0.15),
                  child: const Icon(Icons.person, color: AppColors.gold),
                ),
          const SizedBox(width: AppDimensions.spacingMD),

          // Info
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  booking.barberNama ?? 'Barber',
                  style: const TextStyle(
                    fontWeight: FontWeight.w700,
                    fontSize: 16,
                  ),
                ),
                const SizedBox(height: 2),
                Text(
                  booking.serviceNama ?? 'Service',
                  style: TextStyle(color: AppColors.darkGrey, fontSize: 13),
                ),
                const SizedBox(height: 4),
                Row(
                  children: [
                    const Icon(Icons.calendar_today, size: 12, color: AppColors.mediumGrey),
                    const SizedBox(width: 4),
                    Text(
                      '${Formatters.dateShort(booking.tanggal)} at ${Formatters.time12h(booking.jam)}',
                      style: TextStyle(color: AppColors.mediumGrey, fontSize: 12),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ],
      ),
    ).animate(delay: 100.ms).fadeIn().slideY(begin: 0.1);
  }

  // ─── Interactive Star Rating ────────────────────────────────────────
  Widget _buildStarRating() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.center,
      children: List.generate(5, (index) {
        final starIndex = index + 1;
        final isSelected = _selectedRating >= starIndex;

        return GestureDetector(
          onTap: () => setState(() => _selectedRating = starIndex),
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 4),
            child: AnimatedSwitcher(
              duration: const Duration(milliseconds: 200),
              child: Icon(
                isSelected ? Icons.star : Icons.star_border,
                key: ValueKey('star_$starIndex$_selectedRating'),
                color: isSelected ? AppColors.starFilled : AppColors.starEmpty,
                size: 48,
              ),
            ),
          ),
        );
      }),
    ).animate(delay: 200.ms).fadeIn().scale(
          begin: const Offset(0.8, 0.8),
          end: const Offset(1, 1),
        );
  }

  /// Get rating label based on selected rating
  String _getRatingLabel(int rating) {
    switch (rating) {
      case 1:
        return 'Poor';
      case 2:
        return 'Fair';
      case 3:
        return 'Good';
      case 4:
        return 'Very Good';
      case 5:
        return 'Excellent';
      default:
        return 'Tap to rate';
    }
  }

  // ─── Comment Field ─────────────────────────────────────────────────
  Widget _buildCommentField() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text(
          'Leave a comment (optional)',
          style: TextStyle(
            fontWeight: FontWeight.w600,
            fontSize: 15,
          ),
        ),
        const SizedBox(height: AppDimensions.spacingSM),
        TextField(
          controller: _commentController,
          maxLines: 4,
          maxLength: 500,
          decoration: InputDecoration(
            hintText: 'Share your experience with this barber...',
            filled: true,
            fillColor: AppColors.white,
            border: OutlineInputBorder(
              borderRadius: BorderRadius.circular(AppDimensions.radiusMD),
              borderSide: BorderSide.none,
            ),
            contentPadding: const EdgeInsets.all(AppDimensions.spacingLG),
          ),
        ),
      ],
    ).animate(delay: 300.ms).fadeIn();
  }

  // ─── Submit Button ─────────────────────────────────────────────────
  Widget _buildSubmitButton(BookingModel booking) {
    return SizedBox(
      width: double.infinity,
      height: AppDimensions.buttonHeightLG,
      child: ElevatedButton(
        onPressed: _isSubmitting || _selectedRating == 0
            ? null
            : () => _submitReview(booking),
        style: ElevatedButton.styleFrom(
          backgroundColor: AppColors.primaryBlack,
          foregroundColor: AppColors.white,
          disabledBackgroundColor: AppColors.lightGrey,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(AppDimensions.radiusMD),
          ),
        ),
        child: _isSubmitting
            ? const SizedBox(
                width: 24,
                height: 24,
                child: CircularProgressIndicator(
                  color: AppColors.gold,
                  strokeWidth: 2,
                ),
              )
            : const Text(
                'Submit Review',
                style: TextStyle(
                  fontSize: 16,
                  fontWeight: FontWeight.w700,
                ),
              ),
      ),
    ).animate(delay: 400.ms).fadeIn();
  }

  // ─── Already Rated State ───────────────────────────────────────────
  Widget _buildAlreadyRated(BuildContext context) {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(AppDimensions.spacingXXL),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(
              Icons.check_circle,
              size: 80,
              color: AppColors.successGreen,
            ),
            const SizedBox(height: AppDimensions.spacingLG),
            Text(
              'Already Reviewed',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: AppDimensions.spacingSM),
            Text(
              'You have already rated this booking. Thank you!',
              style: TextStyle(color: AppColors.darkGrey),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppDimensions.spacingXL),
            ElevatedButton(
              onPressed: () => context.go(RouteNames.customerBooking),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primaryBlack,
                foregroundColor: AppColors.white,
              ),
              child: const Text('Back to Bookings'),
            ),
          ],
        ),
      ),
    );
  }
}
